/* Auto-generated by genmsg_cpp for file /home/hossein/rtab_ws/sandbox/marvel_v_0_1/srv/qr_kill.srv */
#ifndef MARVEL_V_0_1_SERVICE_QR_KILL_H
#define MARVEL_V_0_1_SERVICE_QR_KILL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace marvel_v_0_1
{
template <class ContainerAllocator>
struct qr_killRequest_ {
  typedef qr_killRequest_<ContainerAllocator> Type;

  qr_killRequest_()
  : a(0)
  , b(0)
  {
  }

  qr_killRequest_(const ContainerAllocator& _alloc)
  : a(0)
  , b(0)
  {
  }

  typedef int64_t _a_type;
  int64_t a;

  typedef int64_t _b_type;
  int64_t b;


  typedef boost::shared_ptr< ::marvel_v_0_1::qr_killRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marvel_v_0_1::qr_killRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct qr_killRequest
typedef  ::marvel_v_0_1::qr_killRequest_<std::allocator<void> > qr_killRequest;

typedef boost::shared_ptr< ::marvel_v_0_1::qr_killRequest> qr_killRequestPtr;
typedef boost::shared_ptr< ::marvel_v_0_1::qr_killRequest const> qr_killRequestConstPtr;



template <class ContainerAllocator>
struct qr_killResponse_ {
  typedef qr_killResponse_<ContainerAllocator> Type;

  qr_killResponse_()
  : sum(0)
  {
  }

  qr_killResponse_(const ContainerAllocator& _alloc)
  : sum(0)
  {
  }

  typedef int64_t _sum_type;
  int64_t sum;


  typedef boost::shared_ptr< ::marvel_v_0_1::qr_killResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marvel_v_0_1::qr_killResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct qr_killResponse
typedef  ::marvel_v_0_1::qr_killResponse_<std::allocator<void> > qr_killResponse;

typedef boost::shared_ptr< ::marvel_v_0_1::qr_killResponse> qr_killResponsePtr;
typedef boost::shared_ptr< ::marvel_v_0_1::qr_killResponse const> qr_killResponseConstPtr;


struct qr_kill
{

typedef qr_killRequest Request;
typedef qr_killResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct qr_kill
} // namespace marvel_v_0_1

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::marvel_v_0_1::qr_killRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::marvel_v_0_1::qr_killRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::marvel_v_0_1::qr_killRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "36d09b846be0b371c5f190354dd3153e";
  }

  static const char* value(const  ::marvel_v_0_1::qr_killRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x36d09b846be0b371ULL;
  static const uint64_t static_value2 = 0xc5f190354dd3153eULL;
};

template<class ContainerAllocator>
struct DataType< ::marvel_v_0_1::qr_killRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "marvel_v_0_1/qr_killRequest";
  }

  static const char* value(const  ::marvel_v_0_1::qr_killRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::marvel_v_0_1::qr_killRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 a\n\
int64 b\n\
\n\
";
  }

  static const char* value(const  ::marvel_v_0_1::qr_killRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::marvel_v_0_1::qr_killRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::marvel_v_0_1::qr_killResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::marvel_v_0_1::qr_killResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::marvel_v_0_1::qr_killResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const  ::marvel_v_0_1::qr_killResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::marvel_v_0_1::qr_killResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "marvel_v_0_1/qr_killResponse";
  }

  static const char* value(const  ::marvel_v_0_1::qr_killResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::marvel_v_0_1::qr_killResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 sum\n\
\n\
\n\
";
  }

  static const char* value(const  ::marvel_v_0_1::qr_killResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::marvel_v_0_1::qr_killResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::marvel_v_0_1::qr_killRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.a);
    stream.next(m.b);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct qr_killRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::marvel_v_0_1::qr_killResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.sum);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct qr_killResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<marvel_v_0_1::qr_kill> {
  static const char* value() 
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const marvel_v_0_1::qr_kill&) { return value(); } 
};

template<>
struct DataType<marvel_v_0_1::qr_kill> {
  static const char* value() 
  {
    return "marvel_v_0_1/qr_kill";
  }

  static const char* value(const marvel_v_0_1::qr_kill&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<marvel_v_0_1::qr_killRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const marvel_v_0_1::qr_killRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<marvel_v_0_1::qr_killRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "marvel_v_0_1/qr_kill";
  }

  static const char* value(const marvel_v_0_1::qr_killRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<marvel_v_0_1::qr_killResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const marvel_v_0_1::qr_killResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<marvel_v_0_1::qr_killResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "marvel_v_0_1/qr_kill";
  }

  static const char* value(const marvel_v_0_1::qr_killResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // MARVEL_V_0_1_SERVICE_QR_KILL_H

